# ./docker-compose.yml
version: "3"
services:
  frontend:
    build: .
    image:  mosoo_react
    container_name: mosoo_react
    ports:
      - 80:80
    environment:
      REACT_APP_API_BASE_URL: ${REACT_APP_API_BASE_URL}
    networks:
      - shared-network

networks:
  shared-network:
    external: true