version: "3"
services:
  frontend:
    image: ${DOCKER_USER}/mosoo_react:latest
    container_name: mosoo_react
    ports:
      - "80:80"
    environment:
      - REACT_APP_API_BASE_URL=${REACT_APP_API_BASE_URL}
    networks:
      - app-network
    volumes:
      -/path/to/your/project/react/etc/nginx/mosoo.conf:/etc/nginx/mosoo.conf

networks:
  app-network:
    external: true  # 외부 네트워크를 사용